### ISSUE TITLE
Error during generation ONVIF-Monitor example

### ISSUE THREAD

**Issue by wallerka77** [Tereius/libONVIF#12]
Hello Björn,

I am really sorry that I need your help once again.

Actually I wanted to bother you with this problem, but unfortunately I can't get any further on, because some errors occured.

I have logged this once:
[ONVIF-Monitor-Errors.txt](https://github.com/Tereius/libONVIF/files/5724199/ONVIF-Monitor-Errors.txt)
[CMakeOutput.log](https://github.com/Tereius/libONVIF/files/5724206/CMakeOutput.log)

Thanks a lot
Walter

**Comment by Tereius** [comment]
I'm sorry but I can't guide you through every step to get ONVIFMonitor running on a raspberry-pi. It's more elaborate than it seems and will take many hours. You probably have to improve the [conan Qt recipe](https://github.com/Tereius/conan-Qt/blob/master/conanfile.py) so Qt finds the broadcom GLESv2 implementation for full hardware acceleration (actually I always use a cross compiler for raspbian because the native compiler will take probably 6 hours to compile Qt). Then you probably have to fix the [conan QtAV recipe](https://github.com/Tereius/conan-QtAV) so it compiles on a raspberry-pi, or you can patch the recipe so it uses the Qt installation provided by the raspbian os so you can save yourself the trouble with building Qt yourself. Many paths lead to the goal but one needs an understanding of Linux, gcc, binutils, conan and CMake and the Qt build process.

Long story short: Why do you want to use c/c++ and Qt in the first place? Would it not be easier to use a high lvl framework like Electron?
If you want to go further down the road with c/c++ and Qt on raspbian, android or god forbid on ios (all the devices you don't compile natively for but use a cross compiler) you will experience many many hurdles.

When I find the time (if ever) I will have a look at ONVIFMonitor on raspbian. But I will probably use Qt6 because I already have a working [raspbian toolchain and cross compiler](https://github.com/Tereius/conan-raspbian) for my [Qt6 recipe](https://github.com/Tereius/conan-Qt/tree/v6.0).

One more thing: Please open issues in the project where they belong to. This issue has nothing to do with libONVIF but with ONVIFMonitor. So this issue doesn't belong here.

Best greetings
Björn

**Comment by wallerka77** [comment]
Hello Björn,
I apologize for putting the error message in the wrong project. 
Is it possible to delete this issue in the project?

I will now open this issue in the correct project.
As you rightly noticed, I am not a specialist in make-files or linux-libs.
However, I did not contact you directly about the bug.
I had fixed some bugs before with the help of internet research and so on. 
Only with the last problem I just couldn't get any further.

I work with Qt, because I have written other functions in Qt, which I wanted to combine with your ONVIF-Monitor.
In addition, I did not know Electron until now. How does Electron etc. look like with real-time programming?

Unfortunately it doesn't look good with your ONVIF-Monitor for me.
Also, you had said before that you don't want to work on this topic with new functions. 
Therefore I do not want to annoy you of course.

I have birthday today (65) and will distract myself a little and then will try to solve the problem again.

At this point again many thanks for your really great support!

All the best
Walter
